### PR TITLE
Add OMPython as submodule

### PR DESCRIPTION
**Pull request by lochel**

### CODE REVIEW

**Comment by bilderbuchi** [comment]
Shouldn't that preferably be a dependency that you pull in/require via setup.py? Otherwise you maybe end up with 2 installed ompythons, one from your OM Installation, and one from the jupyter kernel?

**Comment by lochel** [comment]
I don’t have much experience with Python and didn’t understand what the `setup.py` script is actually doing. It couldn’t write the kernel.json file on my machine which made it useless for me anyway. 

However, it may be appropriate to handle everything in the setup.py.

**Comment by bilderbuchi** [comment]
setup.py should install the kernel when running `python setup.py install`. 
> It couldn’t write the kernel.json file on my machine

What was the exact problem encountered and the error message? [This line](https://github.com/OpenModelica/jupyter-openmodelica/blob/102ba69f91c1f8e133b546ac97123b6597036dd5/setup.py#L25) should create an OM directory in your [user directory](https://jupyter-client.readthedocs.io/en/latest/kernels.html#kernel-specs) to write the kernel.json file in. What happens if you run the following
``` 
from jupyter_client.kernelspec import KernelSpecManager
KernelSpecManager().user_kernel_dir()
```
in a python console?

setup.py is the standard way to handle package installation and also dependency resolution. In this case, you should add the package's dependencies in an `install_requires` key, like [OMPython does](https://github.com/OpenModelica/OMPython/blob/259006f7d810425efd26b306797d08607b280ce0/setup.py#L66), with the dependencies `OMPython` and `jupyter`. This should automatically install jupyter and OMPython.

**Comment by lochel** [comment]
I see! Thanks for the explanations. Just for the records:

```bash
> python setup.py install
running install
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/openmodelica_kernel
copying openmodelica_kernel/kernel.py -> build/lib.linux-x86_64-2.7/openmodelica_kernel
copying openmodelica_kernel/__init__.py -> build/lib.linux-x86_64-2.7/openmodelica_kernel
copying openmodelica_kernel/__main__.py -> build/lib.linux-x86_64-2.7/openmodelica_kernel
copying openmodelica_kernel/dygraph-combined.js -> build/lib.linux-x86_64-2.7/openmodelica_kernel
running install_lib
creating /usr/local/lib/python2.7/dist-packages/openmodelica_kernel
error: could not create '/usr/local/lib/python2.7/dist-packages/openmodelica_kernel': Permission denied
```

Btw: What is the build directory used for?

**Comment by sjoelund** [comment]
With Python you can build the .pyc or the pip package as a regular user using the build folder. Then you use the root user to install the package. Much like configure/make/sudo make install does. You can also install the Python packages into your local /home folder.

**Comment by bilderbuchi** [comment]
> error: could not create '/usr/local/lib/python2.7/dist-packages/openmodelica_kernel'

ok, this is not about the kernel.json at all, this message means that it wants to install `openmodelica_kernel` into your *system python* package directory, which it can't to because of permissions. 
You should normally be able to use something like `python -m pip install --user .` (mind the dot!) in the package directory to a) use pip for installing which is generally a good idea and b) tell pip to install the package in the user directory. 
I say normally, because it works for idiomatic python packages, and I don't know if there are any strange aspects of the ompython install process left.

Edit: Ha, you should also be able to just append `--user` to the command you used to achieve the same thing: `python setup.py install --user`

**Comment by thorade** [comment]
Adding OMPython to the install_requires section is also part of PR #9.
Instead of running setup.py directly, it is also possible to install via pip, as described in PR #7:
https://github.com/thorade/jupyter-openmodelica/blob/75983402008587a0e78d3ff07371d8236ee8ccfb/README.rst#installation

**Pull request closed without merging**
