### PR TITLE
install_requires

### LINKED ISSUE #8: Numpy dependency not recorded
This is a really bite-sized issue. The dependency on numpy is not reflected in setup.py's `install_requires`. 

At the same time a dependency on OMPython should be added. Here, a minimum OMPython could maybe be set such that the requirement of OpenModelica >1.12.0 (see #5) could be codified in that way (since OMPython comes with Openmodelica, right?)

### PR DESCRIPTION
**Pull request by thorade**
this should close #8 

also ran autopep8, mostly whitespace

### CODE REVIEW

**Comment by thorade** [comment]
To see the PR without whitespace, append `?w=1` to the URL:
https://github.com/OpenModelica/jupyter-openmodelica/pull/9/files?w=1
https://github.com/OpenModelica/jupyter-openmodelica/pull/9/files

**Comment by thorade** [comment]
Note: If people install the jupyter kernel without having installed OMPython before, 
then pip will install the OMPython from PyPI:
https://pypi.python.org/pypi/OMPython

**Comment by bilderbuchi** [comment]
Is the ompython version on pypi compatible with this packages? If not, it might make sense to constrain the version number a bit, and get folks to upload a new ompython release to pypi.

**Comment by thorade** [comment]
The jupyter kernel uses the ZMQ session, and the OMPython that is on PyPI does not yet support ZMQ.
So yes, it would be good to push a new OMPython release to PyPI. 
Or, just not include it in the install_requires list.

**Comment by thorade** [comment]
https://github.com/OpenModelica/OMPython/issues/52 should be addressed before merging this.

**Comment by thorade** [comment]
https://github.com/OpenModelica/OMPython/issues/52 has been addressed, so this PR could be merged, too.

**Comment by thorade** [comment]
Could this get merged?

**Pull request merged**
